version: '3.1'

services:

  mongo:
    image: mongo:3
    restart: always
    expose:
      - "27017"
    # ports:
    #  - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend/
    expose:
      - "4100"
    # ports:
    #  - "4100:4100"

  backend:
    depends_on:
      - mongo
    build: ./backend/
    environment:
      - MONGODB_URI=mongodb://conduit_mongo_1/conduit
    #  - NODE_ENV=production
    expose:
      - "3000"
    # ports:
    #  - "3000:3000"

  proxy:
    depends_on:
      - frontend
      - backend
    build: ./proxy/
    expose:
      - "80"
    ports:
      - "80:80"

volumes:
  mongo-data:
